import React, { Component } from 'react'

import Snakke from 'react-snakke'

export default class App extends Component {
  render () {
    return (
      <div className="wrapper">

        <Snakke color="#a6505a" />

        <header>
          <div className="header-content">
            <img src="https://user-images.githubusercontent.com/2853428/53923774-33b04300-4058-11e9-869e-609617127781.png" />

            <div className="button-wrapper">
              <a className="button" href="https://github.com/diogomoretti/react-snakke" target="_blank">View on github</a>
            </div>
          </div>

          <span className="scroll-indicator">
            <span className="scroll-indicator__line"></span>
              Scroll
            </span>
        </header>

        <div className="demo">
          <h1>React Snakke demo</h1>

          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vitae lacinia leo. Proin et lorem porta, dapibus lorem at, lobortis diam. Curabitur pulvinar nunc a dolor tincidunt mollis. Integer viverra nisi odio. Sed ultricies metus ante, eu facilisis nisi maximus eu. Vivamus vel posuere nunc. In tincidunt dolor ante, sit amet vulputate nisl gravida at. Nam sit amet vehicula eros, non malesuada urna. Maecenas placerat efficitur nulla nec malesuada. In dignissim posuere sodales. Phasellus tempor orci euismod, euismod enim ac, lacinia metus. Fusce feugiat congue est. Donec ornare risus lacus, eu vehicula neque elementum vitae.</p>
          <p>Sed faucibus, eros ac vehicula sollicitudin, justo tortor fringilla enim, sed bibendum risus risus a dolor. Ut volutpat condimentum turpis, sed interdum purus porta non. Nunc et odio bibendum, maximus odio non, ultricies ex. Nullam volutpat, mi vel pretium laoreet, metus felis aliquam dolor, nec ultricies turpis leo a velit. Ut lacinia laoreet maximus. Vivamus sapien ante, auctor in porta interdum, malesuada non mi. Nam aliquam tellus ac sem venenatis, sagittis rhoncus velit rhoncus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Pellentesque aliquam nulla id enim condimentum ultrices. Ut in lacus viverra odio pharetra tincidunt. Morbi ultrices lorem in rutrum scelerisque.</p>
          <p>Nam imperdiet, justo et scelerisque sollicitudin, tortor mi vestibulum odio, ac bibendum magna arcu at nibh. Sed auctor felis non magna bibendum, ut ornare eros pellentesque. Donec lacinia nulla vel mollis mattis. Nam tempus a leo ac interdum. Sed vitae faucibus mauris, at aliquet orci. Phasellus sem nunc, vehicula nec nisi a, rutrum lobortis risus. Sed sagittis nibh sit amet nulla porttitor, sed placerat nisi mollis. Nulla facilisi. Proin accumsan elit at turpis ultrices tincidunt.</p>
          <p>Ut accumsan sapien dui, quis tempor nisl sodales ut. Aliquam in blandit erat. Morbi ac sem varius, ullamcorper ante eu, finibus magna. Maecenas pharetra orci et lacus elementum porta. Nunc scelerisque sit amet dolor ac convallis. Aenean in mi non nisl porta porta. Aenean erat quam, dapibus dapibus dignissim et, viverra in nibh. Nullam mi nulla, tristique a commodo eget, lacinia vel dui. Phasellus vitae lacinia tellus, ut pharetra elit. In blandit eros ac augue tempor, ac lacinia neque finibus. Cras at tellus vitae turpis bibendum fermentum eget et enim. Ut scelerisque, turpis ultrices vulputate consequat, dui magna interdum urna, id posuere mi enim vitae nisi.</p>
          <p>Nunc vitae dignissim arcu, vel commodo purus. Donec tincidunt nisl ac orci pretium, et facilisis orci malesuada. Praesent eget dui eu arcu laoreet eleifend. Aenean ac rutrum arcu, et fringilla augue. Sed ullamcorper justo vitae magna placerat, id iaculis diam malesuada. Nulla ut felis urna. Donec et tortor erat. Maecenas iaculis libero tortor, non accumsan nisl feugiat vitae. In auctor a orci non efficitur. Sed porta felis ac lorem fringilla aliquam. Nunc eros odio, consectetur vitae massa eu, sagittis auctor nisl.</p>
          <p>Donec varius ligula ut congue molestie. In hac habitasse platea dictumst. Cras elit nunc, volutpat ac euismod non, luctus a magna. Etiam mattis aliquet rhoncus. Sed aliquam viverra tellus ut porta. Pellentesque orci neque, rutrum at feugiat vel, accumsan ac eros. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas fermentum dui velit, pellentesque pretium velit tincidunt at. Nulla vitae ornare ipsum. Quisque fringilla dolor quis tempor aliquam. Donec et ante ut nisi porttitor commodo eget eget turpis. Donec gravida odio cursus ante consequat scelerisque. Fusce pretium ligula fringilla eros venenatis malesuada.</p>
          <p>Etiam eget justo non metus pretium feugiat vel in erat. Sed tincidunt, risus eget pharetra rutrum, enim lectus tristique metus, non eleifend dui dui non libero. Fusce non porttitor tellus, quis rhoncus urna. Nulla aliquam a nulla vel hendrerit. Donec eget mollis tortor. Fusce leo orci, imperdiet non felis ut, tincidunt consequat dolor. Cras ultricies semper lectus, vel consequat ligula sodales eget. Maecenas vel posuere neque, in viverra augue. Mauris scelerisque tortor non tincidunt accumsan. Suspendisse sit amet neque nec dui feugiat faucibus. Quisque lobortis, justo ut pretium sollicitudin, lectus leo eleifend odio, sed placerat felis felis et dolor. Duis a fermentum nunc.</p>
          <p>Nullam lacus nibh, ornare non lacinia sed, dignissim ut augue. Pellentesque ultricies ligula arcu, sit amet venenatis mauris scelerisque id. In a cursus dolor, sit amet porta ligula. Suspendisse magna dolor, eleifend sed urna in, rhoncus vestibulum ex. Praesent luctus ante a nulla accumsan, sed ullamcorper libero tempor. Integer condimentum id neque eu cursus. Maecenas porta et lectus ultrices facilisis. Sed vel dui sed velit luctus volutpat eget fringilla leo. Sed justo risus, lacinia eu laoreet at, congue ut ligula. Phasellus turpis felis, fringilla eu auctor eu, congue vitae purus. Cras consectetur dui massa, a placerat felis scelerisque non. Etiam et lorem in dui commodo lacinia id ut enim. Curabitur quis cursus nisi. In tempus congue massa ac pretium.</p>
          <p>Donec vitae lorem quis turpis pellentesque pellentesque eu at neque. Cras ac finibus nulla. Nunc id rutrum dui. Praesent risus arcu, sollicitudin iaculis erat sed, sollicitudin finibus arcu. Proin metus justo, volutpat et blandit sit amet, consequat eget lacus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Curabitur dapibus eu erat at fringilla. Ut hendrerit lorem ut libero lacinia, sodales blandit odio finibus. Phasellus molestie iaculis fermentum.</p>
          <p>Curabitur facilisis mollis gravida. Vestibulum velit turpis, dignissim et metus nec, luctus vehicula augue. Maecenas non mauris pulvinar, ultrices massa quis, egestas neque. Ut id tellus dui. Donec sagittis mauris et nisi feugiat, placerat lacinia est lacinia. Nullam lectus sem, pellentesque vulputate erat ut, maximus accumsan ex. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec posuere hendrerit sapien sed bibendum. Vivamus lobortis, nisl quis consequat vehicula, lacus tortor finibus diam, non interdum dolor urna nec lorem. </p>

          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vitae lacinia leo. Proin et lorem porta, dapibus lorem at, lobortis diam. Curabitur pulvinar nunc a dolor tincidunt mollis. Integer viverra nisi odio. Sed ultricies metus ante, eu facilisis nisi maximus eu. Vivamus vel posuere nunc. In tincidunt dolor ante, sit amet vulputate nisl gravida at. Nam sit amet vehicula eros, non malesuada urna. Maecenas placerat efficitur nulla nec malesuada. In dignissim posuere sodales. Phasellus tempor orci euismod, euismod enim ac, lacinia metus. Fusce feugiat congue est. Donec ornare risus lacus, eu vehicula neque elementum vitae.</p>
          <p>Sed faucibus, eros ac vehicula sollicitudin, justo tortor fringilla enim, sed bibendum risus risus a dolor. Ut volutpat condimentum turpis, sed interdum purus porta non. Nunc et odio bibendum, maximus odio non, ultricies ex. Nullam volutpat, mi vel pretium laoreet, metus felis aliquam dolor, nec ultricies turpis leo a velit. Ut lacinia laoreet maximus. Vivamus sapien ante, auctor in porta interdum, malesuada non mi. Nam aliquam tellus ac sem venenatis, sagittis rhoncus velit rhoncus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Pellentesque aliquam nulla id enim condimentum ultrices. Ut in lacus viverra odio pharetra tincidunt. Morbi ultrices lorem in rutrum scelerisque.</p>
          <p>Nam imperdiet, justo et scelerisque sollicitudin, tortor mi vestibulum odio, ac bibendum magna arcu at nibh. Sed auctor felis non magna bibendum, ut ornare eros pellentesque. Donec lacinia nulla vel mollis mattis. Nam tempus a leo ac interdum. Sed vitae faucibus mauris, at aliquet orci. Phasellus sem nunc, vehicula nec nisi a, rutrum lobortis risus. Sed sagittis nibh sit amet nulla porttitor, sed placerat nisi mollis. Nulla facilisi. Proin accumsan elit at turpis ultrices tincidunt.</p>
          <p>Ut accumsan sapien dui, quis tempor nisl sodales ut. Aliquam in blandit erat. Morbi ac sem varius, ullamcorper ante eu, finibus magna. Maecenas pharetra orci et lacus elementum porta. Nunc scelerisque sit amet dolor ac convallis. Aenean in mi non nisl porta porta. Aenean erat quam, dapibus dapibus dignissim et, viverra in nibh. Nullam mi nulla, tristique a commodo eget, lacinia vel dui. Phasellus vitae lacinia tellus, ut pharetra elit. In blandit eros ac augue tempor, ac lacinia neque finibus. Cras at tellus vitae turpis bibendum fermentum eget et enim. Ut scelerisque, turpis ultrices vulputate consequat, dui magna interdum urna, id posuere mi enim vitae nisi.</p>
          <p>Nunc vitae dignissim arcu, vel commodo purus. Donec tincidunt nisl ac orci pretium, et facilisis orci malesuada. Praesent eget dui eu arcu laoreet eleifend. Aenean ac rutrum arcu, et fringilla augue. Sed ullamcorper justo vitae magna placerat, id iaculis diam malesuada. Nulla ut felis urna. Donec et tortor erat. Maecenas iaculis libero tortor, non accumsan nisl feugiat vitae. In auctor a orci non efficitur. Sed porta felis ac lorem fringilla aliquam. Nunc eros odio, consectetur vitae massa eu, sagittis auctor nisl.</p>
          <p>Donec varius ligula ut congue molestie. In hac habitasse platea dictumst. Cras elit nunc, volutpat ac euismod non, luctus a magna. Etiam mattis aliquet rhoncus. Sed aliquam viverra tellus ut porta. Pellentesque orci neque, rutrum at feugiat vel, accumsan ac eros. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas fermentum dui velit, pellentesque pretium velit tincidunt at. Nulla vitae ornare ipsum. Quisque fringilla dolor quis tempor aliquam. Donec et ante ut nisi porttitor commodo eget eget turpis. Donec gravida odio cursus ante consequat scelerisque. Fusce pretium ligula fringilla eros venenatis malesuada.</p>
          <p>Etiam eget justo non metus pretium feugiat vel in erat. Sed tincidunt, risus eget pharetra rutrum, enim lectus tristique metus, non eleifend dui dui non libero. Fusce non porttitor tellus, quis rhoncus urna. Nulla aliquam a nulla vel hendrerit. Donec eget mollis tortor. Fusce leo orci, imperdiet non felis ut, tincidunt consequat dolor. Cras ultricies semper lectus, vel consequat ligula sodales eget. Maecenas vel posuere neque, in viverra augue. Mauris scelerisque tortor non tincidunt accumsan. Suspendisse sit amet neque nec dui feugiat faucibus. Quisque lobortis, justo ut pretium sollicitudin, lectus leo eleifend odio, sed placerat felis felis et dolor. Duis a fermentum nunc.</p>
          <p>Nullam lacus nibh, ornare non lacinia sed, dignissim ut augue. Pellentesque ultricies ligula arcu, sit amet venenatis mauris scelerisque id. In a cursus dolor, sit amet porta ligula. Suspendisse magna dolor, eleifend sed urna in, rhoncus vestibulum ex. Praesent luctus ante a nulla accumsan, sed ullamcorper libero tempor. Integer condimentum id neque eu cursus. Maecenas porta et lectus ultrices facilisis. Sed vel dui sed velit luctus volutpat eget fringilla leo. Sed justo risus, lacinia eu laoreet at, congue ut ligula. Phasellus turpis felis, fringilla eu auctor eu, congue vitae purus. Cras consectetur dui massa, a placerat felis scelerisque non. Etiam et lorem in dui commodo lacinia id ut enim. Curabitur quis cursus nisi. In tempus congue massa ac pretium.</p>
          <p>Donec vitae lorem quis turpis pellentesque pellentesque eu at neque. Cras ac finibus nulla. Nunc id rutrum dui. Praesent risus arcu, sollicitudin iaculis erat sed, sollicitudin finibus arcu. Proin metus justo, volutpat et blandit sit amet, consequat eget lacus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Curabitur dapibus eu erat at fringilla. Ut hendrerit lorem ut libero lacinia, sodales blandit odio finibus. Phasellus molestie iaculis fermentum.</p>
          <p>Curabitur facilisis mollis gravida. Vestibulum velit turpis, dignissim et metus nec, luctus vehicula augue. Maecenas non mauris pulvinar, ultrices massa quis, egestas neque. Ut id tellus dui. Donec sagittis mauris et nisi feugiat, placerat lacinia est lacinia. Nullam lectus sem, pellentesque vulputate erat ut, maximus accumsan ex. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec posuere hendrerit sapien sed bibendum. Vivamus lobortis, nisl quis consequat vehicula, lacus tortor finibus diam, non interdum dolor urna nec lorem. </p>

          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vitae lacinia leo. Proin et lorem porta, dapibus lorem at, lobortis diam. Curabitur pulvinar nunc a dolor tincidunt mollis. Integer viverra nisi odio. Sed ultricies metus ante, eu facilisis nisi maximus eu. Vivamus vel posuere nunc. In tincidunt dolor ante, sit amet vulputate nisl gravida at. Nam sit amet vehicula eros, non malesuada urna. Maecenas placerat efficitur nulla nec malesuada. In dignissim posuere sodales. Phasellus tempor orci euismod, euismod enim ac, lacinia metus. Fusce feugiat congue est. Donec ornare risus lacus, eu vehicula neque elementum vitae.</p>
          <p>Sed faucibus, eros ac vehicula sollicitudin, justo tortor fringilla enim, sed bibendum risus risus a dolor. Ut volutpat condimentum turpis, sed interdum purus porta non. Nunc et odio bibendum, maximus odio non, ultricies ex. Nullam volutpat, mi vel pretium laoreet, metus felis aliquam dolor, nec ultricies turpis leo a velit. Ut lacinia laoreet maximus. Vivamus sapien ante, auctor in porta interdum, malesuada non mi. Nam aliquam tellus ac sem venenatis, sagittis rhoncus velit rhoncus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Pellentesque aliquam nulla id enim condimentum ultrices. Ut in lacus viverra odio pharetra tincidunt. Morbi ultrices lorem in rutrum scelerisque.</p>
          <p>Nam imperdiet, justo et scelerisque sollicitudin, tortor mi vestibulum odio, ac bibendum magna arcu at nibh. Sed auctor felis non magna bibendum, ut ornare eros pellentesque. Donec lacinia nulla vel mollis mattis. Nam tempus a leo ac interdum. Sed vitae faucibus mauris, at aliquet orci. Phasellus sem nunc, vehicula nec nisi a, rutrum lobortis risus. Sed sagittis nibh sit amet nulla porttitor, sed placerat nisi mollis. Nulla facilisi. Proin accumsan elit at turpis ultrices tincidunt.</p>
          <p>Ut accumsan sapien dui, quis tempor nisl sodales ut. Aliquam in blandit erat. Morbi ac sem varius, ullamcorper ante eu, finibus magna. Maecenas pharetra orci et lacus elementum porta. Nunc scelerisque sit amet dolor ac convallis. Aenean in mi non nisl porta porta. Aenean erat quam, dapibus dapibus dignissim et, viverra in nibh. Nullam mi nulla, tristique a commodo eget, lacinia vel dui. Phasellus vitae lacinia tellus, ut pharetra elit. In blandit eros ac augue tempor, ac lacinia neque finibus. Cras at tellus vitae turpis bibendum fermentum eget et enim. Ut scelerisque, turpis ultrices vulputate consequat, dui magna interdum urna, id posuere mi enim vitae nisi.</p>
          <p>Nunc vitae dignissim arcu, vel commodo purus. Donec tincidunt nisl ac orci pretium, et facilisis orci malesuada. Praesent eget dui eu arcu laoreet eleifend. Aenean ac rutrum arcu, et fringilla augue. Sed ullamcorper justo vitae magna placerat, id iaculis diam malesuada. Nulla ut felis urna. Donec et tortor erat. Maecenas iaculis libero tortor, non accumsan nisl feugiat vitae. In auctor a orci non efficitur. Sed porta felis ac lorem fringilla aliquam. Nunc eros odio, consectetur vitae massa eu, sagittis auctor nisl.</p>
          <p>Donec varius ligula ut congue molestie. In hac habitasse platea dictumst. Cras elit nunc, volutpat ac euismod non, luctus a magna. Etiam mattis aliquet rhoncus. Sed aliquam viverra tellus ut porta. Pellentesque orci neque, rutrum at feugiat vel, accumsan ac eros. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas fermentum dui velit, pellentesque pretium velit tincidunt at. Nulla vitae ornare ipsum. Quisque fringilla dolor quis tempor aliquam. Donec et ante ut nisi porttitor commodo eget eget turpis. Donec gravida odio cursus ante consequat scelerisque. Fusce pretium ligula fringilla eros venenatis malesuada.</p>
          <p>Etiam eget justo non metus pretium feugiat vel in erat. Sed tincidunt, risus eget pharetra rutrum, enim lectus tristique metus, non eleifend dui dui non libero. Fusce non porttitor tellus, quis rhoncus urna. Nulla aliquam a nulla vel hendrerit. Donec eget mollis tortor. Fusce leo orci, imperdiet non felis ut, tincidunt consequat dolor. Cras ultricies semper lectus, vel consequat ligula sodales eget. Maecenas vel posuere neque, in viverra augue. Mauris scelerisque tortor non tincidunt accumsan. Suspendisse sit amet neque nec dui feugiat faucibus. Quisque lobortis, justo ut pretium sollicitudin, lectus leo eleifend odio, sed placerat felis felis et dolor. Duis a fermentum nunc.</p>
          <p>Nullam lacus nibh, ornare non lacinia sed, dignissim ut augue. Pellentesque ultricies ligula arcu, sit amet venenatis mauris scelerisque id. In a cursus dolor, sit amet porta ligula. Suspendisse magna dolor, eleifend sed urna in, rhoncus vestibulum ex. Praesent luctus ante a nulla accumsan, sed ullamcorper libero tempor. Integer condimentum id neque eu cursus. Maecenas porta et lectus ultrices facilisis. Sed vel dui sed velit luctus volutpat eget fringilla leo. Sed justo risus, lacinia eu laoreet at, congue ut ligula. Phasellus turpis felis, fringilla eu auctor eu, congue vitae purus. Cras consectetur dui massa, a placerat felis scelerisque non. Etiam et lorem in dui commodo lacinia id ut enim. Curabitur quis cursus nisi. In tempus congue massa ac pretium.</p>
          <p>Donec vitae lorem quis turpis pellentesque pellentesque eu at neque. Cras ac finibus nulla. Nunc id rutrum dui. Praesent risus arcu, sollicitudin iaculis erat sed, sollicitudin finibus arcu. Proin metus justo, volutpat et blandit sit amet, consequat eget lacus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Curabitur dapibus eu erat at fringilla. Ut hendrerit lorem ut libero lacinia, sodales blandit odio finibus. Phasellus molestie iaculis fermentum.</p>
          <p>Curabitur facilisis mollis gravida. Vestibulum velit turpis, dignissim et metus nec, luctus vehicula augue. Maecenas non mauris pulvinar, ultrices massa quis, egestas neque. Ut id tellus dui. Donec sagittis mauris et nisi feugiat, placerat lacinia est lacinia. Nullam lectus sem, pellentesque vulputate erat ut, maximus accumsan ex. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec posuere hendrerit sapien sed bibendum. Vivamus lobortis, nisl quis consequat vehicula, lacus tortor finibus diam, non interdum dolor urna nec lorem. </p>

          <p className="end">End of the pageName ;)</p>
        </div>
      </div>
    )
  }
}
